#pragma once

#define ESC(...) "\x1b[" #__VA_ARGS__ "m"
#define ESC_OFF ESC(0)

#define COLOR_BLK ESC(30)
#define COLOR_RED ESC(31)
#define COLOR_GRN ESC(32)
#define COLOR_YEL ESC(33)
#define COLOR_BLU ESC(34)
#define COLOR_MAG ESC(35)
#define COLOR_CYN ESC(36)
#define COLOR_WHT ESC(37)
#define COLOR_RGB(r, g, b) ESC(38;2;r;g;b)
#define COLOR(code) ESC(38;5;code)
#define COLOR_OFF ESC(39)
#define COLOR_GRY ESC(90)
#define COLOR_BRD ESC(91)
#define COLOR_BGR ESC(92)
#define COLOR_BYL ESC(93)
#define COLOR_BBL ESC(94)
#define COLOR_PNK ESC(95)
#define COLOR_BCY ESC(96)
#define COLOR_BWH ESC(97)

#define BKGRD_BLK ESC(40)
#define BKGRD_RED ESC(41)
#define BKGRD_GRN ESC(42)
#define BKGRD_YEL ESC(43)
#define BKGRD_BLU ESC(44)
#define BKGRD_MAG ESC(45)
#define BKGRD_CYN ESC(46)
#define BKGRD_WHT ESC(47)
#define BKGRD_RGB(r, g, b) ESC(48;2;r;g;b)
#define BKGRD(code) ESC(48;5;code)
#define BKGRD_OFF ESC(49)
#define BKGRD_GRY ESC(100)
#define BKGRD_BRD ESC(101)
#define BKGRD_BGR ESC(102)
#define BKGRD_BYL ESC(103)
#define BKGRD_BBL ESC(104)
#define BKGRD_PNK ESC(105)
#define BKGRD_BCY ESC(106)
#define BKGRD_BWH ESC(107)
